name: nyabugogoride

description: A smart bus ticket booking app for inter-district public transport in Rwanda.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_analytics: ^11.5.2
  provider: ^6.1.1
  flutter_local_notifications: ^19.3.0
  fl_chart: ^1.0.0
  http: ^1.2.1
  image_picker: ^1.0.4
  firebase_storage: ^12.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    
